server:
  port: 8082

spring:
  application:
    name: mall-seckill
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: mall
    password: mall
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
